branch-defaults:
  default:
    environment: redeilpf-prod
environment-defaults:
  redeilpf-prod:
    branch: null
    repository: null
global:
  application_name: rede_ilpf
  default_ec2_keyname: redeilpf
  default_platform: python-3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
