branch-defaults:
  default:
    environment: redeilpf-prod
global:
  application_name: rede_ilpf
  branch: null
  default_ec2_keyname: redeilpf
  default_platform: python-3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
